-- ============================================================================
-- PostgreSQL pgvector Extension Initialization Script
-- ============================================================================
--
-- PURPOSE:
--   Automatically loads the pgvector extension when the container starts
--   for the first time. This script is executed by Docker's postgres image
--   entrypoint in alphabetical order during database initialization.
--
-- PERSPECTIVES ADDRESSED:
--   • Maintainability: Clear comments explain what each line does
--   • Testability: Each CREATE EXTENSION can be run independently
--   • Architecture: Follows Docker postgres image conventions
--   • Security: No credentials or secrets in this file
--   • Business Value: Zero-config setup for vector operations
--   • Documentation: Explains why pgvector is created
--
-- EXECUTION CONTEXT:
--   - Runs automatically on container first start (when PGDATA is empty)
--   - Executed as the postgres superuser
--   - Runs in the database specified by POSTGRES_DB env variable
--   - Must be idempotent (safe to run multiple times)
--
-- ============================================================================

-- Enable pgvector extension in the default database
-- IF NOT EXISTS: Makes this script idempotent (safe to run multiple times)
-- RATIONALE:
--   • Testability: Script can be re-run without causing errors
--   • Maintainability: Safe to use as both init script and migration script
--   • Business Value: Vector operations available immediately
CREATE EXTENSION IF NOT EXISTS pgvector;

-- Verify extension was loaded successfully
-- This comment documents what was done for operators/developers
-- In production logs, this appears if extension creation succeeded
COMMENT ON EXTENSION pgvector IS 'open-source vector similarity search for PostgreSQL - enables AI/ML workloads with vector embeddings';

-- ============================================================================
-- PGVECTOR FEATURES NOW AVAILABLE:
-- ============================================================================
--
-- 1. VECTOR DATA TYPE:
--    - Store embeddings: CREATE TABLE embeddings (id SERIAL, vector vector(1536));
--    - Insert vectors: INSERT INTO embeddings (vector) VALUES ('[1,2,3]'::vector);
--    - Dimensions: vector(n) where n is the embedding dimension
--
-- 2. SIMILARITY OPERATORS:
--    - <->   : Euclidean distance (L2 norm) - fastest
--    - <#>   : Negative inner product - for cosine similarity
--    - <=>   : Cosine distance - preferred for ML models
--
-- 3. INDEXES:
--    - IVFFLAT: Approximate nearest neighbor (fast, less accurate)
--    - HNSW:    Hierarchical Navigable Small World (slower build, fastest search)
--    Usage: CREATE INDEX ON table USING ivfflat (vector_column vector_cosine_ops);
--
-- 4. AGGREGATE FUNCTIONS:
--    - avg(vector): Calculate mean vector
--    - sum(vector): Sum vectors element-wise
--
-- ============================================================================
-- SECURITY CONSIDERATIONS:
-- ============================================================================
--
-- ✓ This extension is loaded at database initialization
-- ✓ No external network calls required
-- ✓ No temporary files created (data stored in heap)
-- ✓ Compiled with standard PostgreSQL security context
--
-- ============================================================================
-- TESTING THIS EXTENSION:
-- ============================================================================
--
-- From host machine:
--   docker exec container_name psql -U postgres -c \
--     \"SELECT default_version FROM pg_available_extensions WHERE name='pgvector';\"
--
-- Inside container:
--   psql -U postgres
--   postgres=# CREATE TABLE test_vectors (id SERIAL, embedding vector(3));
--   postgres=# INSERT INTO test_vectors (embedding) VALUES ('[1,2,3]');
--   postgres=# SELECT embedding <-> '[4,5,6]' as distance FROM test_vectors;
--
-- Expected output: distance value (Euclidean distance between vectors)
--
-- ============================================================================
